version: '2'
services:
  mysqlmaster1:
    image: mysql:5.7.15
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysqlmaster1:/var/lib/mysql/
      - ./config/mysqlmaster1:/etc/mysql/conf.d/
  mysqlmaster2:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysqlmaster2:/var/lib/mysql/
      - ./config/mysqlmaster2:/etc/mysql/conf.d/
  mysqlconfigure:
    image: mysql:5.7.15
    environment:
      - "MYSQL_MASTER1_PASSWORD=root"
      - "MYSQL_MASTER2_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh
